VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "qarham/ubuntu-1604-250G"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.provision "shell", path: "../scripts/resolve-conf.sh"
  config.vm.provision "shell", path: "../scripts/ntp.sh"
  config.vm.provision "shell", path: "../scripts/enable_root_login.sh"
  config.vm.provision "shell", path: "../scripts/aio-helm-deployer.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 12884
    vb.cpus = 6
    vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]
    vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
  end

  config.vm.define "aio-node", primary: true do |aio|
    aio.vm.network "public_network", bridge: "br0", ip: "10.13.82.240"
    aio.vm.provision "shell",inline: "route add default gw 10.13.82.1"
    aio.vm.provision "shell",inline: "eval `route -n | awk '{ if ($8 ==\"enp0s3\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"  
    aio.vm.hostname = "aio-node"
  end
end
